// Copyright IBM Corp. 2024, 2025
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.15.6
// source: plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PluginSetupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client_capabilities should be populated by the client to indicate which
	// behaviours the client is aware of.
	ClientCapabilities *PluginSetupRequest_ClientCapabilities `protobuf:"bytes,1,opt,name=client_capabilities,json=clientCapabilities,proto3" json:"client_capabilities,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PluginSetupRequest) Reset() {
	*x = PluginSetupRequest{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginSetupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginSetupRequest) ProtoMessage() {}

func (x *PluginSetupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginSetupRequest.ProtoReflect.Descriptor instead.
func (*PluginSetupRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *PluginSetupRequest) GetClientCapabilities() *PluginSetupRequest_ClientCapabilities {
	if x != nil {
		return x.ClientCapabilities
	}
	return nil
}

type PluginSetupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// server_capabilities will be populated by the server to indicate which
	// behaviours the client should expect from the server.
	ServerCapabilities *PluginSetupResponse_ServerCapabilities `protobuf:"bytes,1,opt,name=server_capabilities,json=serverCapabilities,proto3" json:"server_capabilities,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PluginSetupResponse) Reset() {
	*x = PluginSetupResponse{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginSetupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginSetupResponse) ProtoMessage() {}

func (x *PluginSetupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginSetupResponse.ProtoReflect.Descriptor instead.
func (*PluginSetupResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *PluginSetupResponse) GetServerCapabilities() *PluginSetupResponse_ServerCapabilities {
	if x != nil {
		return x.ServerCapabilities
	}
	return nil
}

// ListFunctionsRequest is the message body for the ListFunctions RPC.
type ListFunctionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFunctionsRequest) Reset() {
	*x = ListFunctionsRequest{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFunctionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFunctionsRequest) ProtoMessage() {}

func (x *ListFunctionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFunctionsRequest.ProtoReflect.Descriptor instead.
func (*ListFunctionsRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

// ListFunctionsResponse is the response body for the ListFunctions RPC.
type ListFunctionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// functions is a map of functions that are available in the plugin.
	Functions     map[string]*Function `protobuf:"bytes,1,rep,name=functions,proto3" json:"functions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFunctionsResponse) Reset() {
	*x = ListFunctionsResponse{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFunctionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFunctionsResponse) ProtoMessage() {}

func (x *ListFunctionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFunctionsResponse.ProtoReflect.Descriptor instead.
func (*ListFunctionsResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ListFunctionsResponse) GetFunctions() map[string]*Function {
	if x != nil {
		return x.Functions
	}
	return nil
}

// ExecuteFunctionRequest is the message body for the ExecuteFunction RPC.
type ExecuteFunctionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name identifies the function to call.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// arguments contains the arguments to the function, msgpack encoded.
	Arguments     [][]byte `protobuf:"bytes,2,rep,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteFunctionRequest) Reset() {
	*x = ExecuteFunctionRequest{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteFunctionRequest) ProtoMessage() {}

func (x *ExecuteFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteFunctionRequest.ProtoReflect.Descriptor instead.
func (*ExecuteFunctionRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteFunctionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExecuteFunctionRequest) GetArguments() [][]byte {
	if x != nil {
		return x.Arguments
	}
	return nil
}

// ExecuteFunctionResponse is the response body for the ExecuteFunction RPC.
type ExecuteFunctionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// result is the result of the function call, msgpack encoded.
	Result        []byte `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteFunctionResponse) Reset() {
	*x = ExecuteFunctionResponse{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteFunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteFunctionResponse) ProtoMessage() {}

func (x *ExecuteFunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteFunctionResponse.ProtoReflect.Descriptor instead.
func (*ExecuteFunctionResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteFunctionResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

// Function provides the definition of a function as it transfers via RPC.
type Function struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The supported parameters of the function.
	Parameters        []*FunctionParameter `protobuf:"bytes,1,rep,name=parameters,proto3" json:"parameters,omitempty"`
	VariadicParameter *FunctionParameter   `protobuf:"bytes,2,opt,name=variadic_parameter,json=variadicParameter,proto3" json:"variadic_parameter,omitempty"`
	// The return type of the function, json encoded.
	ReturnType      []byte `protobuf:"bytes,3,opt,name=return_type,json=returnType,proto3" json:"return_type,omitempty"`
	Description     string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	DescriptionKind string `protobuf:"bytes,5,opt,name=description_kind,json=descriptionKind,proto3" json:"description_kind,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Function) Reset() {
	*x = Function{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Function) ProtoMessage() {}

func (x *Function) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Function.ProtoReflect.Descriptor instead.
func (*Function) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *Function) GetParameters() []*FunctionParameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *Function) GetVariadicParameter() *FunctionParameter {
	if x != nil {
		return x.VariadicParameter
	}
	return nil
}

func (x *Function) GetReturnType() []byte {
	if x != nil {
		return x.ReturnType
	}
	return nil
}

func (x *Function) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Function) GetDescriptionKind() string {
	if x != nil {
		return x.DescriptionKind
	}
	return ""
}

// FunctionParameter provides the definition of a function parameter as it
// transfers via rpc.
type FunctionParameter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The type of the parameter, json encoded.
	Type          []byte `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Description   string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AllowNull     bool   `protobuf:"varint,4,opt,name=allow_null,json=allowNull,proto3" json:"allow_null,omitempty"`
	AllowUnknown  bool   `protobuf:"varint,5,opt,name=allow_unknown,json=allowUnknown,proto3" json:"allow_unknown,omitempty"`
	AllowDynamic  bool   `protobuf:"varint,6,opt,name=allow_dynamic,json=allowDynamic,proto3" json:"allow_dynamic,omitempty"`
	AllowMarked   bool   `protobuf:"varint,7,opt,name=allow_marked,json=allowMarked,proto3" json:"allow_marked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionParameter) Reset() {
	*x = FunctionParameter{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionParameter) ProtoMessage() {}

func (x *FunctionParameter) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionParameter.ProtoReflect.Descriptor instead.
func (*FunctionParameter) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *FunctionParameter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionParameter) GetType() []byte {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *FunctionParameter) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FunctionParameter) GetAllowNull() bool {
	if x != nil {
		return x.AllowNull
	}
	return false
}

func (x *FunctionParameter) GetAllowUnknown() bool {
	if x != nil {
		return x.AllowUnknown
	}
	return false
}

func (x *FunctionParameter) GetAllowDynamic() bool {
	if x != nil {
		return x.AllowDynamic
	}
	return false
}

func (x *FunctionParameter) GetAllowMarked() bool {
	if x != nil {
		return x.AllowMarked
	}
	return false
}

// client_capabilities should be populated by the client to indicate which
// behaviours the client is aware of.
type PluginSetupRequest_ClientCapabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginSetupRequest_ClientCapabilities) Reset() {
	*x = PluginSetupRequest_ClientCapabilities{}
	mi := &file_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginSetupRequest_ClientCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginSetupRequest_ClientCapabilities) ProtoMessage() {}

func (x *PluginSetupRequest_ClientCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginSetupRequest_ClientCapabilities.ProtoReflect.Descriptor instead.
func (*PluginSetupRequest_ClientCapabilities) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0, 0}
}

// server_capabilities will be populated by the server to indicate which
// behaviours the client should expect from the server.
type PluginSetupResponse_ServerCapabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginSetupResponse_ServerCapabilities) Reset() {
	*x = PluginSetupResponse_ServerCapabilities{}
	mi := &file_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginSetupResponse_ServerCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginSetupResponse_ServerCapabilities) ProtoMessage() {}

func (x *PluginSetupResponse_ServerCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginSetupResponse_ServerCapabilities.ProtoReflect.Descriptor instead.
func (*PluginSetupResponse_ServerCapabilities) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1, 0}
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\bprotocol\"\x8c\x01\n" +
	"\x12PluginSetupRequest\x12`\n" +
	"\x13client_capabilities\x18\x01 \x01(\v2/.protocol.PluginSetupRequest.ClientCapabilitiesR\x12clientCapabilities\x1a\x14\n" +
	"\x12ClientCapabilities\"\x8e\x01\n" +
	"\x13PluginSetupResponse\x12a\n" +
	"\x13server_capabilities\x18\x01 \x01(\v20.protocol.PluginSetupResponse.ServerCapabilitiesR\x12serverCapabilities\x1a\x14\n" +
	"\x12ServerCapabilities\"\x16\n" +
	"\x14ListFunctionsRequest\"\xb7\x01\n" +
	"\x15ListFunctionsResponse\x12L\n" +
	"\tfunctions\x18\x01 \x03(\v2..protocol.ListFunctionsResponse.FunctionsEntryR\tfunctions\x1aP\n" +
	"\x0eFunctionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.protocol.FunctionR\x05value:\x028\x01\"J\n" +
	"\x16ExecuteFunctionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\targuments\x18\x02 \x03(\fR\targuments\"1\n" +
	"\x17ExecuteFunctionResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result\"\x81\x02\n" +
	"\bFunction\x12;\n" +
	"\n" +
	"parameters\x18\x01 \x03(\v2\x1b.protocol.FunctionParameterR\n" +
	"parameters\x12J\n" +
	"\x12variadic_parameter\x18\x02 \x01(\v2\x1b.protocol.FunctionParameterR\x11variadicParameter\x12\x1f\n" +
	"\vreturn_type\x18\x03 \x01(\fR\n" +
	"returnType\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12)\n" +
	"\x10description_kind\x18\x05 \x01(\tR\x0fdescriptionKind\"\xe9\x01\n" +
	"\x11FunctionParameter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\fR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"allow_null\x18\x04 \x01(\bR\tallowNull\x12#\n" +
	"\rallow_unknown\x18\x05 \x01(\bR\fallowUnknown\x12#\n" +
	"\rallow_dynamic\x18\x06 \x01(\bR\fallowDynamic\x12!\n" +
	"\fallow_marked\x18\a \x01(\bR\vallowMarked2\xfe\x01\n" +
	"\x06Plugin\x12F\n" +
	"\x05Setup\x12\x1c.protocol.PluginSetupRequest\x1a\x1d.protocol.PluginSetupResponse\"\x00\x12R\n" +
	"\rListFunctions\x12\x1e.protocol.ListFunctionsRequest\x1a\x1f.protocol.ListFunctionsResponse\"\x00\x12X\n" +
	"\x0fExecuteFunction\x12 .protocol.ExecuteFunctionRequest\x1a!.protocol.ExecuteFunctionResponse\"\x00BLZJgithub.com/hashicorp/terraform-policy-plugin-framework/policy-plugin/protob\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_plugin_proto_goTypes = []any{
	(*PluginSetupRequest)(nil),                     // 0: protocol.PluginSetupRequest
	(*PluginSetupResponse)(nil),                    // 1: protocol.PluginSetupResponse
	(*ListFunctionsRequest)(nil),                   // 2: protocol.ListFunctionsRequest
	(*ListFunctionsResponse)(nil),                  // 3: protocol.ListFunctionsResponse
	(*ExecuteFunctionRequest)(nil),                 // 4: protocol.ExecuteFunctionRequest
	(*ExecuteFunctionResponse)(nil),                // 5: protocol.ExecuteFunctionResponse
	(*Function)(nil),                               // 6: protocol.Function
	(*FunctionParameter)(nil),                      // 7: protocol.FunctionParameter
	(*PluginSetupRequest_ClientCapabilities)(nil),  // 8: protocol.PluginSetupRequest.ClientCapabilities
	(*PluginSetupResponse_ServerCapabilities)(nil), // 9: protocol.PluginSetupResponse.ServerCapabilities
	nil, // 10: protocol.ListFunctionsResponse.FunctionsEntry
}
var file_plugin_proto_depIdxs = []int32{
	8,  // 0: protocol.PluginSetupRequest.client_capabilities:type_name -> protocol.PluginSetupRequest.ClientCapabilities
	9,  // 1: protocol.PluginSetupResponse.server_capabilities:type_name -> protocol.PluginSetupResponse.ServerCapabilities
	10, // 2: protocol.ListFunctionsResponse.functions:type_name -> protocol.ListFunctionsResponse.FunctionsEntry
	7,  // 3: protocol.Function.parameters:type_name -> protocol.FunctionParameter
	7,  // 4: protocol.Function.variadic_parameter:type_name -> protocol.FunctionParameter
	6,  // 5: protocol.ListFunctionsResponse.FunctionsEntry.value:type_name -> protocol.Function
	0,  // 6: protocol.Plugin.Setup:input_type -> protocol.PluginSetupRequest
	2,  // 7: protocol.Plugin.ListFunctions:input_type -> protocol.ListFunctionsRequest
	4,  // 8: protocol.Plugin.ExecuteFunction:input_type -> protocol.ExecuteFunctionRequest
	1,  // 9: protocol.Plugin.Setup:output_type -> protocol.PluginSetupResponse
	3,  // 10: protocol.Plugin.ListFunctions:output_type -> protocol.ListFunctionsResponse
	5,  // 11: protocol.Plugin.ExecuteFunction:output_type -> protocol.ExecuteFunctionResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PluginClient is the client API for Plugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PluginClient interface {
	Setup(ctx context.Context, in *PluginSetupRequest, opts ...grpc.CallOption) (*PluginSetupResponse, error)
	// ListFunctions will list all the functions that are available in the plugin.
	ListFunctions(ctx context.Context, in *ListFunctionsRequest, opts ...grpc.CallOption) (*ListFunctionsResponse, error)
	// ExecuteFunction will execute a function in the plugin.
	ExecuteFunction(ctx context.Context, in *ExecuteFunctionRequest, opts ...grpc.CallOption) (*ExecuteFunctionResponse, error)
}

type pluginClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginClient(cc grpc.ClientConnInterface) PluginClient {
	return &pluginClient{cc}
}

func (c *pluginClient) Setup(ctx context.Context, in *PluginSetupRequest, opts ...grpc.CallOption) (*PluginSetupResponse, error) {
	out := new(PluginSetupResponse)
	err := c.cc.Invoke(ctx, "/protocol.Plugin/Setup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) ListFunctions(ctx context.Context, in *ListFunctionsRequest, opts ...grpc.CallOption) (*ListFunctionsResponse, error) {
	out := new(ListFunctionsResponse)
	err := c.cc.Invoke(ctx, "/protocol.Plugin/ListFunctions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) ExecuteFunction(ctx context.Context, in *ExecuteFunctionRequest, opts ...grpc.CallOption) (*ExecuteFunctionResponse, error) {
	out := new(ExecuteFunctionResponse)
	err := c.cc.Invoke(ctx, "/protocol.Plugin/ExecuteFunction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServer is the server API for Plugin service.
type PluginServer interface {
	Setup(context.Context, *PluginSetupRequest) (*PluginSetupResponse, error)
	// ListFunctions will list all the functions that are available in the plugin.
	ListFunctions(context.Context, *ListFunctionsRequest) (*ListFunctionsResponse, error)
	// ExecuteFunction will execute a function in the plugin.
	ExecuteFunction(context.Context, *ExecuteFunctionRequest) (*ExecuteFunctionResponse, error)
}

// UnimplementedPluginServer can be embedded to have forward compatible implementations.
type UnimplementedPluginServer struct {
}

func (*UnimplementedPluginServer) Setup(context.Context, *PluginSetupRequest) (*PluginSetupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Setup not implemented")
}
func (*UnimplementedPluginServer) ListFunctions(context.Context, *ListFunctionsRequest) (*ListFunctionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFunctions not implemented")
}
func (*UnimplementedPluginServer) ExecuteFunction(context.Context, *ExecuteFunctionRequest) (*ExecuteFunctionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteFunction not implemented")
}

func RegisterPluginServer(s *grpc.Server, srv PluginServer) {
	s.RegisterService(&_Plugin_serviceDesc, srv)
}

func _Plugin_Setup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginSetupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Setup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Plugin/Setup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Setup(ctx, req.(*PluginSetupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_ListFunctions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFunctionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).ListFunctions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Plugin/ListFunctions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).ListFunctions(ctx, req.(*ListFunctionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_ExecuteFunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteFunctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).ExecuteFunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Plugin/ExecuteFunction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).ExecuteFunction(ctx, req.(*ExecuteFunctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Plugin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.Plugin",
	HandlerType: (*PluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Setup",
			Handler:    _Plugin_Setup_Handler,
		},
		{
			MethodName: "ListFunctions",
			Handler:    _Plugin_ListFunctions_Handler,
		},
		{
			MethodName: "ExecuteFunction",
			Handler:    _Plugin_ExecuteFunction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}
